version: "3"

services:
    datasc:
        container_name: python-club
        volumes:  
            - ${CODE_DIR}:/code
            - ${CONFIG_DIR}:/config
        environment:
            - JUPYTER_CONFIG_DIR=/config
        ports:
            - "9999:9999"
        build:
            context: "./container"
        image: mclass:v1
        entrypoint: "/bin/bash"
        command: -c "jupyter notebook --ip=0.0.0.0 --no-browser --port 9999 --allow-root"